name: Tests
on: [push]
jobs:

  tests-mods:
    name: ${{matrix.os}} Tests (1.13)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        go mod download
        go mod tidy -v
        go test -race ./...

  tests-112-off:
    name: ${{matrix.os}} Tests (1.12/OFF)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      GO111MODULE: off
      GOPATH: $PWD/go
    steps:
    - name: Set GOPATH
      # temporary fix
      # see https://github.com/actions/setup-go/issues/14
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        export GOPATH=$(go env GOPATH)
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        path: go/src/github.com/${{ github.repository }}
    - name: Test
      run: |
        go get -t -v ./...
        go test -race ./...
