name: Tests
on: [push]
jobs:

  tests-mods:
    name: ${{matrix.os}} Tests (1.13)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      run: |
        go mod download
        go mod tidy -v
        go test -race ./...

  tests-112-off:
    name: ${{matrix.os}} Tests (1.12/OFF)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        os: [macos-latest, windows-latest, ubuntu-latest]
    env:
      GO111MODULE: off
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        path: src/github.com/${{ github.repository }}
    - name: Test
      env:
        GOPATH: ${{github.workspace}}
      run: |
        echo $GOPATH
        go get -t -v ./...
        go test -race ./...
